name: Maintenance
version: '${version}'
main: dev.mznu.maintenance.MaintenancePlugin
description: '${description}'
author: mznu
api-version: '26.2'

commands:
  maintenance:
    description: Manages maintenance mode.
    usage: /maintenance <help|status|on|off|reload|schedule|whitelist>
    aliases: [mt]
    permission: maintenance.command

permissions:
  maintenance.command:
    description: Allows use of maintenance commands.
    default: op
